#!/usr/bin/env python3
"""Classify the inline-45.0f camera-handler sites one at a time.

For each site: enable ONLY that site's instruction patch (66.5f), regenerate,
rebuild, probe the attract demos, and record which projection fovy values the
RT64 telemetry reports plus margin scores of the framebuffer dumps.

A site is a PROJECTION mover if m11 ~= cot(33.25deg) = 1.5268 appears while it
is the only patched site. Culling/tilt classification needs the framebuffers /
an interactive check; dumps are preserved per site as fbsite_<n>_*.bin.
"""
import os
import re
import shutil
import subprocess
import sys
import time

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TOML = os.path.join(REPO, "recomp", "waverace64.toml")
EXE = os.path.join(REPO, "build", "WaveRace64Recomp.exe")
VCVARS = r"C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\Build\vcvars64.bat"

SITES = [
    ("func_8009B910", 0x8009B93C),
    ("func_8009BA14", 0x8009BA40),
    ("func_8009BAE0", 0x8009BB0C),
    ("func_8009BB98", 0x8009BBC4),
    ("func_8009BCA4", 0x8009BCD0),
]

EXPERIMENT_RE = re.compile(
    r"# --- EXPERIMENT \(culling classification\).*?(?=\Z)", re.DOTALL)

PROBE_SECONDS = 55


def write_toml(sites_enabled):
    base = open(TOML, encoding="utf-8").read()
    base = EXPERIMENT_RE.sub("", base).rstrip() + "\n"
    block = ["# --- EXPERIMENT (culling classification): auto-generated by",
             "# scripts/classify_fov_sites.py — do not commit.\n"]
    for func, vram in sites_enabled:
        block.append(f'[[patches.instruction]]\nfunc = "{func}"\nvram = 0x{vram:08X}\nvalue = 0x3C014285 # lui $at, 0x4285 (66.5f)\n')
    open(TOML, "w", encoding="utf-8", newline="\n").write(base + "\n" + "\n".join(block))


def rebuild():
    # One retry: the just-killed game process can briefly hold the exe lock.
    for attempt in range(2):
        if subprocess.call(["cmd", "/c", os.path.join(REPO, "scripts", "rebuild.cmd")]) == 0:
            return True
        time.sleep(5)
    return False


def probe(tag):
    env = os.environ.copy()
    env["WR64_BORDERS"] = "0"
    env["WR64_FB_DUMP"] = "1"
    for f in ("fb_dump.bin", "fb_dump2.bin", "fb_dump3.bin"):
        p = os.path.join(REPO, f)
        if os.path.exists(p):
            os.remove(p)
    err_path = os.path.join(REPO, f"probe_site_{tag}.err.log")
    with open(err_path, "w") as errf:
        proc = subprocess.Popen([EXE], cwd=REPO, stdout=subprocess.DEVNULL, stderr=errf, env=env)
        time.sleep(PROBE_SECONDS)
        if proc.poll() is None:
            proc.kill()
            proc.wait()
    time.sleep(3)  # let the OS release the exe before the next rebuild
    # Harvest telemetry m11 values.
    m11s = set()
    for line in open(err_path, encoding="utf-8", errors="replace"):
        m = re.search(r"m11=([0-9.]+)", line)
        if m:
            m11s.add(round(float(m.group(1)), 3))
    # Preserve dumps.
    scores = []
    for i, f in enumerate(("fb_dump.bin", "fb_dump2.bin", "fb_dump3.bin")):
        src = os.path.join(REPO, f)
        if os.path.exists(src):
            dst = os.path.join(REPO, f"fbsite_{tag}_{i}.bin")
            shutil.copyfile(src, dst)
            out = subprocess.check_output(
                [sys.executable, os.path.join(REPO, "scripts", "score_margins.py"), dst],
                cwd=REPO, text=True)
            scores.append(out.strip())
    return sorted(m11s), scores


def main():
    start = 0
    for arg in sys.argv[1:]:
        if arg.startswith("--start="):
            start = int(arg.split("=")[1])
    results = []
    for idx, site in enumerate(SITES):
        if idx < start:
            continue
        print(f"== site {idx}: {site[0]} @ 0x{site[1]:08X} ==", flush=True)
        write_toml([site])
        if not rebuild():
            print("  BUILD FAILED — aborting", flush=True)
            return 1
        m11s, scores = probe(str(idx))
        wide = any(abs(v - 1.527) < 0.02 for v in m11s)
        print(f"  m11 values: {m11s}  -> 66.5deg projection seen: {wide}", flush=True)
        for s in scores:
            print(f"  {s}", flush=True)
        results.append((site, wide, m11s))

    # Clean toml (no experiment patches) at the end.
    write_toml([])
    print("\n== SUMMARY ==")
    for (func, vram), wide, m11s in results:
        print(f"{func} @ 0x{vram:08X}: projection-mover={wide} m11={m11s}")
    print("(toml left clean; rebuild once more before playing)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
