#!/usr/bin/env python3
"""Round 3: classify the still-unresolved inline-45.0f camera sites using a
real Sunny Beach race (scripts/drive_to_race.ps1) instead of the attract demo.

Rounds 1-2 (scripts/classify_fov_sites.py) left 19 sites classified only as
"no widened m11 seen under attract-demo probing" -- not a confirmed verdict,
since attract mode never exercises most camera setups (see docs/RE-NOTES.md).
This round drives an actual race so per-course/per-mode cameras that are
inactive during attract demos get a real chance to fire.

For each site: enable ONLY that site's instruction patch (66.5f), rebuild,
drive into a live Sunny Beach race, hold the accelerator, and record which
projection fovy values RT64 telemetry reports.
"""
import os
import re
import subprocess
import sys
import time

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TOML = os.path.join(REPO, "recomp", "waverace64.toml")
DRIVE_SCRIPT = os.path.join(REPO, "scripts", "drive_to_race.ps1")

# The 19 sites left unresolved after rounds 1-2 (docs/RE-NOTES.md).
SITES = [
    ("func_8009BA14", 0x8009BA40),
    ("func_8009BAE0", 0x8009BB0C),
    ("func_80089C08", 0x80089C50),
    ("func_8009BEBC", 0x8009BED8),
    ("func_8009BEEC", 0x8009BF08),
    ("func_8009BF1C", 0x8009BF38),
    ("func_8009BF4C", 0x8009BF68),
    ("func_8009BF7C", 0x8009BF98),
    ("func_8009BFAC", 0x8009BFC8),
    ("func_8009BFDC", 0x8009BFF8),
    ("func_8009C00C", 0x8009C028),
    ("func_8009C044", 0x8009C060),
    ("func_8009C074", 0x8009C090),
    ("func_8009C0A4", 0x8009C0C0),
    ("func_8009C0D4", 0x8009C0F0),
    ("func_8009C104", 0x8009C120),
    ("func_8009C134", 0x8009C150),
    ("func_8009C164", 0x8009C180),
    ("func_8009C194", 0x8009C1B0),
]

EXPERIMENT_RE = re.compile(
    r"# --- EXPERIMENT \(culling classification\).*?(?=\Z)", re.DOTALL)


def write_toml(sites_enabled):
    base = open(TOML, encoding="utf-8").read()
    base = EXPERIMENT_RE.sub("", base).rstrip() + "\n"
    block = ["# --- EXPERIMENT (culling classification): auto-generated by",
             "# scripts/classify_fov_sites_race.py — do not commit.\n"]
    for func, vram in sites_enabled:
        block.append(f'[[patches.instruction]]\nfunc = "{func}"\nvram = 0x{vram:08X}\nvalue = 0x3C014285 # lui $at, 0x4285 (66.5f)\n')
    open(TOML, "w", encoding="utf-8", newline="\n").write(base + "\n" + "\n".join(block))


def rebuild():
    for attempt in range(2):
        if subprocess.call(["cmd", "/c", os.path.join(REPO, "scripts", "rebuild.cmd")]) == 0:
            return True
        time.sleep(5)
    return False


def probe(tag):
    out_dir = os.path.join(REPO, f"drive_race_{tag}")
    subprocess.call([
        "powershell", "-NoProfile", "-ExecutionPolicy", "Bypass", "-File", DRIVE_SCRIPT,
        "-AccelerateSeconds", "10", "-OutDir", out_dir,
    ], cwd=REPO)
    time.sleep(3)  # let the OS release the exe before the next rebuild
    err_path = os.path.join(out_dir, "stderr.log")
    m11s = set()
    if os.path.exists(err_path):
        for line in open(err_path, encoding="utf-8", errors="replace"):
            m = re.search(r"m11=([0-9.]+)", line)
            if m:
                m11s.add(round(float(m.group(1)), 3))
    return sorted(m11s)


def main():
    start = 0
    for arg in sys.argv[1:]:
        if arg.startswith("--start="):
            start = int(arg.split("=")[1])
    results = []
    for idx, site in enumerate(SITES):
        if idx < start:
            continue
        print(f"== site {idx}: {site[0]} @ 0x{site[1]:08X} ==", flush=True)
        write_toml([site])
        if not rebuild():
            print("  BUILD FAILED — aborting", flush=True)
            return 1
        m11s = probe(str(idx))
        wide = any(abs(v - 1.527) < 0.02 for v in m11s)
        print(f"  m11 values: {m11s}  -> 66.5deg projection seen: {wide}", flush=True)
        results.append((site, wide, m11s))

    write_toml([])
    print("\n== SUMMARY ==")
    for (func, vram), wide, m11s in results:
        print(f"{func} @ 0x{vram:08X}: projection-mover={wide} m11={m11s}")
    print("(toml left clean; rebuild once more before playing)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
