#!/usr/bin/env python3
"""Generate patches/syms.ld from the recomp symbol TOML.

Gives the MIPS patches linker the address of every known game function so
patch code can call into the game. Run whenever the syms TOML changes:
    python scripts/generate_syms_ld.py
"""

import re

SYMS_PATH = "recomp/waverace64.us.rev1.syms.toml"
OUT_PATH = "patches/syms.ld"

HEADER = """/* Generated by scripts/generate_syms_ld.py from {src} -- do not edit. */
__start = 0x80000000;

/* Native runtime imports live at dummy addresses (0x8F000000+) and are
   registered via recomp::overlays::register_manual_patch_symbols. */
"""

text = open(SYMS_PATH, "r", encoding="utf-8").read()
pattern = re.compile(
    r'\[\[section\.functions\]\]\s*\nname = "([^"]+)"\s*\nvram = (0x[0-9A-Fa-f]+)'
)

lines = []
seen = set()
for m in pattern.finditer(text):
    name, vram = m.group(1), m.group(2)
    if name in seen:
        continue
    seen.add(name)
    lines.append(f"{name} = {vram};")

with open(OUT_PATH, "w", encoding="utf-8", newline="\n") as f:
    f.write(HEADER.format(src=SYMS_PATH))
    f.write("\n".join(lines))
    f.write("\n")

print(f"wrote {OUT_PATH}: {len(lines)} symbols")
