#!/usr/bin/env python3
"""Group-bisection probe for the in-race fovy source (round 4).

Rounds 1-3 (classify_fov_sites*.py) confirmed 4 projection movers among the
23 sites tested — but none of them is the RACE camera: with only those 4
patched, a real race still shows m11=2.414 (45 deg). The race mover must be
among the ~28 untested sites (0x8009C1F0 + the 0x800Axxx/0x800Bxxx block).

This script patches an arbitrary GROUP of sites (by index into ALL_SITES,
e.g. "0-13" or "3,7,9"), rebuilds, drives one real Sunny Beach race
(scripts/drive_to_race.ps1), and reports whether m11 ~= 2.256 (47.75 deg)
appeared — bisect manually from the outside, ~5 runs instead of 28.

Usage: python scripts/probe_fov_group.py 0-27        # all untested
       python scripts/probe_fov_group.py 0-13        # first half
       python scripts/probe_fov_group.py clean       # remove patches only
"""
import os
import re
import subprocess
import sys
import time

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TOML = os.path.join(REPO, "recomp", "waverace64.toml")
DRIVE_SCRIPT = os.path.join(REPO, "scripts", "drive_to_race.ps1")

# The 28 sites never tested in rounds 1-3, in gen_fov_patches.py order.
# (func, vram, register-preserving 47.75f lui word from gen_fov_patches.py.)
ALL_SITES = [
    ("func_8009C1C4", 0x8009C1F0),
    ("func_800A52D8", 0x800A54E4),
    ("func_800A52D8", 0x800A5648),
    ("func_800A52D8", 0x800A57AC),
    ("func_800A52D8", 0x800A57B8),
    ("func_800A5D70", 0x800A610C),
    ("func_800A5D70", 0x800A6264),
    ("func_800A68A4", 0x800A6D9C),
    ("func_800A68A4", 0x800A6EE4),
    ("func_800A68A4", 0x800A6EF0),
    ("func_800A68A4", 0x800A7460),
    ("func_800A68A4", 0x800A75A8),
    ("func_800A68A4", 0x800A75C0),
    ("func_800A68A4", 0x800A8328),
    ("func_800A68A4", 0x800A8658),
    ("func_800A68A4", 0x800A8664),
    ("func_800A68A4", 0x800A8E24),
    ("func_800A68A4", 0x800A8E30),
    ("func_800A9494", 0x800A96B0),
    ("func_800A9494", 0x800A978C),
    ("func_800A9494", 0x800A9878),
    ("func_800A9494", 0x800A9884),
    ("func_800A9D48", 0x800AA5EC),
    ("func_800A9D48", 0x800AA814),
    ("func_800AAAC8", 0x800AAF7C),
    ("func_800AB25C", 0x800AB62C),
    ("func_800AC184", 0x800AD1B4),
    ("func_800B08F8", 0x800B1E70),
    ("func_800B08F8", 0x800B1F1C),
]

EXPERIMENT_RE = re.compile(
    r"# --- EXPERIMENT \(race-fovy group bisect\).*?(?=\Z)", re.DOTALL)

REGS = {
    "$zero": 0, "$at": 1, "$v0": 2, "$v1": 3, "$a0": 4, "$a1": 5, "$a2": 6, "$a3": 7,
    "$t0": 8, "$t1": 9, "$t2": 10, "$t3": 11, "$t4": 12, "$t5": 13, "$t6": 14, "$t7": 15,
    "$s0": 16, "$s1": 17, "$s2": 18, "$s3": 19, "$s4": 20, "$s5": 21, "$s6": 22, "$s7": 23,
    "$t8": 24, "$t9": 25, "$k0": 26, "$k1": 27, "$gp": 28, "$sp": 29, "$fp": 30, "$ra": 31,
}


def find_patch_word(vram):
    """Find the site's target register in RecompiledFuncs and build the
    register-preserving 47.75f lui word (same approach as gen_fov_patches.py)."""
    import glob
    # Match 0x4234 (original 45.0f) OR 0x423F (already patched to 47.75f in a
    # previous run — RecompiledFuncs gets regenerated with patches applied).
    site_re = re.compile(r"// 0x%08X: lui\s+(\$\w+), 0x423[4F]" % vram)
    for path in glob.glob(os.path.join(REPO, "RecompiledFuncs", "funcs_*.c")):
        for line in open(path, encoding="utf-8", errors="replace"):
            m = site_re.search(line)
            if m:
                return 0x3C000000 | (REGS[m.group(1)] << 16) | 0x423F, m.group(1)
    raise SystemExit(f"site 0x{vram:08X} not found in RecompiledFuncs")


def write_toml(indices):
    base = open(TOML, encoding="utf-8").read()
    base = EXPERIMENT_RE.sub("", base).rstrip() + "\n"
    if not indices:
        open(TOML, "w", encoding="utf-8", newline="\n").write(base)
        return
    block = ["# --- EXPERIMENT (race-fovy group bisect): auto-generated by",
             "# scripts/probe_fov_group.py — do not commit.\n"]
    for i in indices:
        func, vram = ALL_SITES[i]
        word, reg = find_patch_word(vram)
        block.append(f'[[patches.instruction]]\nfunc = "{func}"\nvram = 0x{vram:08X}\nvalue = 0x{word:08X} # lui {reg}, 0x423F (47.75f, was 45.0f) [site {i}]\n')
    open(TOML, "w", encoding="utf-8", newline="\n").write(base + "\n" + "\n".join(block))


def parse_indices(spec):
    out = []
    for part in spec.split(","):
        if "-" in part:
            a, b = part.split("-")
            out.extend(range(int(a), int(b) + 1))
        else:
            out.append(int(part))
    return sorted(set(out))


def main():
    if len(sys.argv) != 2:
        print(__doc__)
        return 1
    if sys.argv[1] == "clean":
        write_toml([])
        print("experiment patches removed (rebuild to apply)")
        return 0
    indices = parse_indices(sys.argv[1])
    print(f"patching {len(indices)} sites: {indices}", flush=True)
    write_toml(indices)
    for attempt in range(2):
        if subprocess.call(["cmd", "/c", os.path.join(REPO, "scripts", "rebuild.cmd")]) == 0:
            break
        time.sleep(5)
    else:
        print("BUILD FAILED")
        return 1
    out_dir = os.path.join(REPO, "drive_group_probe")
    subprocess.call([
        "powershell", "-NoProfile", "-ExecutionPolicy", "Bypass", "-File", DRIVE_SCRIPT,
        "-AccelerateSeconds", "10", "-OutDir", out_dir,
    ], cwd=REPO)
    m11s = set()
    err_path = os.path.join(out_dir, "stderr.log")
    for line in open(err_path, encoding="utf-8", errors="replace"):
        m = re.search(r"m11=([0-9.]+)", line)
        if m:
            m11s.add(round(float(m.group(1)), 3))
    hit = any(abs(v - 2.256) < 0.02 for v in m11s)
    print(f"m11 values: {sorted(m11s)}")
    print(f"RESULT: 47.75deg in race = {hit}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
